# Workflow's name
name: linux-clang

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  linux-clang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Installing premake5
        uses: Jarod42/install-premake5@v1
      - name: Build
        run: |
          premake5 build
      - name: Test
        run: chmod +x moon && ./moon example/test/main_test.lua