
# Workflow's name
name: macos-clang

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  macos-clang:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          brew install premake
          premake5 build
      - name: Test
        run: chmod +x moon && ./moon test/main_test.lua
