
# Workflow's name
name: windows-vs2022

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  windows-vs2022:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Installing premake5
        uses: Jarod42/install-premake5@v1
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: |
          premake5 build
      - name: Test
        run: .\moon.exe test/main_test.lua

